### ISSUE TITLE
how to download hugo_extended version?

### ISSUE THREAD

**Issue by goldcoders** [webinstall/webi-installer-requests#49]
Hi i see in https://webinstall.dev/api/releases/hugo@.tab
that there is a hugo extended version
but i dont see a way to use webi to install the hugo extended version on webi
i tried webi hugo_extended@v.0.89.2
or webi hugo@beta 
or webi hugo@extended_v.0.89.2

**Comment by coolaj86** [comment]
hugo-extended is now available at https://webinstall.dev/hugo-extended as of webinstall/webi-installers#650
