### ISSUE TITLE
READ ME FIRST: How to Contribute

### ISSUE THREAD

**Issue by coolaj86** [webinstall/webi-installer-requests#65]
Each of these issues needs to follow the same basic format:

0. Take a look at
   - [webinstall.dev](https://webinstall.dev) to understand the project goals
   - [How Can I Contribute](https://github.com/webinstall/webi-installers/issues/661) for overall project guidelines
2. Is the requested tool a good fit for Webi?
   - has official binary releases \
     (or well-known 3rd party release)
   - binary releases are single-file (like Caddy, rg, bat) 
   - or a self-contained package (like Node, Go, Flutter)
   - they DO NOT require dependencies (no `apt-get install whateverlib`)
3. Can a beginner add this tool easily?
   - binary releases are available via GitHub Releases or Gitea Releases
   - or releases are scripts available purely as Source code
   - is there an existing installer in the same basic format? \
     (see [The Installer Matrix](https://github.com/webinstall/webi-installers/issues/412))
4. Am _I_ the right person to add this tool?
   - do you personally use the tool?
   - can you effectively communicate its best qualities in a cheat sheet?
   - or can you at least get the installer portion working via copy/paste/edit?

**Comment by coolaj86** [comment]
Closing because this isn't an action item, but rather a sticky discussion / documentation.

**Comment by hazem19952025** [comment]
Hazem khatab
