### ISSUE TITLE
Request for github cli

### ISSUE THREAD

**Issue by wesleycoder** [webinstall/webi-installer-requests#81]
Always several different steps to install this so much used tool on different systems.
Webi would be so much welcomed to have this one.

https://github.com/cli/cli/blob/trunk/docs/install_linux.md

**Comment by coolaj86** [comment]
Why not use the updated version?

https://webinstall.dev/gh

**Comment by coolaj86** [comment]
Oh, that is the updated version (GitHub had another repo also named something similar to`cli` for the previous version)

In any case, since we already had it but it wasn't clear to you:

What were you searching for?

**Comment by coolaj86** [comment]
Also: could you open a PR on the GitHub docs to add Webi?

**Comment by wesleycoder** [comment]
whoah, that one I really missed (my bad, sry 😅 )

Sure, I'll open the PR for the docs.

Thanks for the quick response 😃
